
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("projects_categories/new", "Create projects_categories")) ?>
</div>

<?php echo $this->tag->form(array("projects_categories/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search projects_categories</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="project_id">Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="category_id">Category</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("category_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
