
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("projects/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("projects", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit projects</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="investment">Investment</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("investment", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="implementation_period">Implementation Of Period</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("implementation_period", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
