<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap 101 Template</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
  <link href="../css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="../css/jasny-bootstrap.min.css" rel="stylesheet" media="screen">

  <!-- Custom styles for this template -->
  <link href="../css/navmenu.css" rel="stylesheet">
  <link href="../css/gt.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>


<body>

<div class="navbar navbar-default navbar-fixed-top hidden-md hidden-lg">
  <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">Project name</a>
</div>

<div class="container-fluid gt-menuTop">
  <div class="navbar-header">
    <ul class="nav pull-left">
      <li class="dropdown">
        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-gestion"></i><strong>Gestion
            2014</strong><i class="caret"></i>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a tabindex="-1" href="#">Gesti&oacute;n 2013</a>
          </li>
          <li class="divider"></li>
          <li>
            <a tabindex="-1" href="login.html">Gesti&oacute;n 2012</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav pull-right">
      <li class="dropdown">
        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> Milton
          Loayza <i class="caret"></i></a>
        <ul class="dropdown-menu">
          <li>
            <a tabindex="-1" href="#">Configuracion</a>
          </li>
          <li class="divider"></li>
          <li>
            <a tabindex="-1" href="login.html">Salir</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>
<div class="container-fluid">
  <!--BEGIN CUERPO DE LA PAGINA-->
  <!--<div class="page-header">-->
  <!--<h1>Navmenu Template</h1>-->
  <!--</div>-->



  <?php echo $this->tag->form("projects/create") ?>

  <?php echo $this->getContent(); ?>

  <div align="center">
    <h1>Create projects</h1>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="">Nombre de Proyecto</label>
        <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group has-feedback">
        <label class="control-label" for="frmLocalizacion">Localizacion</label>
        <input type="text" class="form-control" id="frmLocalizacion" placeholder="">
        <span class="glyphicon glyphicon-ok form-control-feedback"></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="">Entidad Financiera</label>
        <select class="form-control">
          <option value="">Seleccionar Entidad financiera</option>
          <option value="">Ninguno</option>
        </select>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label for="">Tipo de Proyecto</label>
        <select class="form-control">
          <option value="">Seleccionar Tipo de Proyecto</option>
          <option value="">Ninguno</option>
        </select>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label for="">Periodo de Realizacion</label>
        <?php echo $this->tag->textField(array("implementation_period", "size" => 30, 'class' => 'form-control')) ?>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label for="">Inversion</label>
        <?php echo $this->tag->textField(array("investment", "size" => 30, 'class' => 'form-control')) ?>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label for="">Descripcion del Proyecto</label>
        <?php echo $this->tag->textArea(array(
          "description",
          "description here",
          "type" => "date",
          'class' => 'form-control',
          "rows" => 3
        )) ?>

      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label for="">Impacto Social</label>
        <textarea class="form-control" rows="3"></textarea>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group text-right">
        <?php echo $this->tag->submitButton(array(
          'value' => "Agregar proyecto",
          'class' => 'btn btn-lg btn-success'
        )) ?>
      </div>
    </div>
  </div>
  </form>


  <!--<form class="navbar-form navbar-right" role="form">-->
  <!--</form>-->
  <!--<p class="lead">This example shows the navmenu element. If the viewport is <b>less than 992px</b> the menu will be placed the off canvas and will be shown with a slide in effect.</p>-->
  <!--<p>Also take a look at the examples for a navmenu with <a href="../navmenu-push">push effect</a> and <a href="../navmenu-reveal">reveal effect</a>.</p>-->
</div>
<!-- /.container -->

<!--END CUERPO DE LA PAGINA-->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script src="js/jasny-bootstrap.min.js"></script>

<script>
  $(document).ready(function () {
    $('ul.tree').hide();

    $('label.tree-toggler').click(function () {
      $(this).parent().children('ul.tree').toggle(300);
    });
  });
</script>
</body>
</html>
