<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap 101 Template</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
  <link href="../css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="../css/jasny-bootstrap.min.css" rel="stylesheet" media="screen">

  <!-- Custom styles for this template -->
  <link href="../css/navmenu.css" rel="stylesheet">
  <link href="../css/gt.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>


<body>


<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("projects/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("projects/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Investment</th>
            <th>Implementation Of Period</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $project) { ?>
        <tr>
            <td><?php echo $project->id ?></td>
            <td><?php echo $project->name ?></td>
            <td><?php echo $project->description ?></td>
            <td><?php echo $project->investment ?></td>
            <td><?php echo $project->implementation_period ?></td>
            <td><?php echo $this->tag->linkTo(array("projects/edit/" . $project->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("projects/delete/" . $project->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("projects/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>


<div class="container-fluid bgBlueGray txtWhite">
  <div class="col-md-12 h4">Municipio de La Paz / <strong>Proyectos de Urbanismo y Vivienda</strong></div>
</div>

<div class="jumbotron">

  <div class="row">
    <div class="col-lg-12">

      <div class="list-group">
        <a href="#" class="list-group-item">
          <div class="row">
            <div class="col-lg-2">
              <img data-src="holder.js/180x180" class="img-thumbnail" alt="">
            </div>
            <div class="col-lg-10">
              <h2 class="list-group-item-heading">PROYECTO: MI TELEFERICO</h2>
              <p class="list-group-item-text txtLightBlue">Ranking del Proyecto <span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span></p>
              <!--<p class="list-group-item-text">...</p>-->
              <p class="list-group-item-text">Vestibulum sit amet augue id nunc vestibulum sollicitudin. Suspendisse venenatis laoreet orci vitae posuere. Pellentesque ac interdum enim. Integer id sagittis erat. Aliquam in nulla odio. Sed posuere in lacus sed iaculis. Donec laoreet metus ac commodo fringilla. Etiam quis nunc posuere, placerat mi vel, dictum dui.</p>
            </div>
          </div>
        </a>
        <a href="#" class="list-group-item">
          <div class="row">
            <div class="col-lg-2">
              <img data-src="holder.js/180x180" class="img-thumbnail" alt="">
            </div>
            <div class="col-lg-10">
              <h2 class="list-group-item-heading">PROYECTO: MIZICUNI</h2>
              <p class="list-group-item-text txtLightBlue">Ranking del Proyecto <span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span></p>
              <!--<p class="list-group-item-text">...</p>-->
              <p class="list-group-item-text">Vestibulum sit amet augue id nunc vestibulum sollicitudin. Suspendisse venenatis laoreet orci vitae posuere. Pellentesque ac interdum enim. Integer id sagittis erat. Aliquam in nulla odio. Sed posuere in lacus sed iaculis. Donec laoreet metus ac commodo fringilla. Etiam quis nunc posuere, placerat mi vel, dictum dui.</p>
            </div>
          </div>
        </a>
        <a href="#" class="list-group-item">
          <div class="row">
            <div class="col-lg-2">
              <img data-src="holder.js/180x180" class="img-thumbnail" alt="">
            </div>
            <div class="col-lg-10">
              <h2 class="list-group-item-heading">PROYECTO: STADIUM HERNANDO SILEZ</h2>
              <p class="list-group-item-text txtLightBlue">Ranking del Proyecto <span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star"></span></p>
              <!--<p class="list-group-item-text">...</p>-->
              <p class="list-group-item-text">Vestibulum sit amet augue id nunc vestibulum sollicitudin. Suspendisse venenatis laoreet orci vitae posuere. Pellentesque ac interdum enim. Integer id sagittis erat. Aliquam in nulla odio. Sed posuere in lacus sed iaculis. Donec laoreet metus ac commodo fringilla. Etiam quis nunc posuere, placerat mi vel, dictum dui.</p>
            </div>
          </div>
        </a>
      </div>

      <ul class="pagination pagination-lg">
        <li><a href="#">«</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">»</a></li>
      </ul>
    </div>
  </div>

</div>

<script src="js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script src="js/jasny-bootstrap.min.js"></script>

<script>
  $(document).ready(function () {
    $('ul.tree').hide();

    $('label.tree-toggler').click(function () {
      $(this).parent().children('ul.tree').toggle(300);
    });
  });
</script>
</body>
</html>


