<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("projects/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("projects/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Investment</th>
            <th>Implementation Of Period</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $project) { ?>
        <tr>
            <td><?php echo $project->id ?></td>
            <td><?php echo $project->name ?></td>
            <td><?php echo $project->description ?></td>
            <td><?php echo $project->investment ?></td>
            <td><?php echo $project->implementation_period ?></td>
            <td><?php echo $this->tag->linkTo(array("projects/edit/" . $project->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("projects/delete/" . $project->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("projects/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("projects/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
