
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("similar_projects/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("similar_projects", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<div align="center">
    <h1>Edit similar_projects</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="similar_project_id">Similar Of Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("similar_project_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
