
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("similar_projects/new", "Create similar_projects")) ?>
</div>

<?php echo $this->tag->form(array("similar_projects/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search similar_projects</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="similar_project_id">Similar Of Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("similar_project_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
