<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("similar_projects/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("similar_projects/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Similar Of Project</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $similar_project) { ?>
        <tr>
            <td><?php echo $similar_project->id ?></td>
            <td><?php echo $similar_project->similar_project_id ?></td>
            <td><?php echo $this->tag->linkTo(array("similar_projects/edit/" . $similar_project->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("similar_projects/delete/" . $similar_project->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("similar_projects/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("similar_projects/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("similar_projects/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("similar_projects/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
