
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("gestions/new", "Create gestions")) ?>
</div>

<?php echo $this->tag->form(array("gestions/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search gestions</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="budget">Budget</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("budget", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
