
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("categories/new", "Create categories")) ?>
</div>

<?php echo $this->tag->form(array("categories/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search categories</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="category_parent_id">Category Of Parent</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("category_parent_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="weight">Weight</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("weight", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
