<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("categories/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("categories/new", "Create ")); ?>
        </td>
    <tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Category Of Parent</th>
            <th>Weight</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $categorie) { ?>
        <tr>
            <td><?php echo $categorie->id ?></td>
            <td><?php echo $categorie->name ?></td>
            <td><?php echo $categorie->category_parent_id ?></td>
            <td><?php echo $categorie->weight ?></td>
            <td><?php echo $this->tag->linkTo(array("categories/edit/" . $categorie->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("categories/delete/" . $categorie->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("categories/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("categories/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("categories/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("categories/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
