
<?php echo $this->tag->form("projects_blogs/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("projects_blogs", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    <tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create projects_blogs</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="project_id">Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
